In [1]:
# 导入写的kkn脚本
from mlutils.knn import KNNClassifier

In [2]:
import numpy as np

In [3]:
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

In [4]:
knn_classifier = KNNClassifier(6)

In [5]:
knn_classifier.fit(X_train, y_train)

In [6]:
x = np.array([8.08, 3.36])
x_predict = x.reshape(1, -1)
x_predict

array([[8.08, 3.36]])

In [7]:
knn_classifier.predict(x_predict)

array([1])

In [8]:
from mlutils.train_test_split import train_test_split

In [9]:
from sklearn import datasets

In [10]:
iris = datasets.load_iris()

In [11]:
X = iris.data

In [12]:
y = iris.target

In [13]:
X_train , y_train, X_test, y_test = train_test_split(X, y)

In [14]:
X_train.shape

(120, 4)

In [15]:
y_train.shape

(120,)

In [16]:
X_test.shape

(30, 4)

In [17]:
y_test.shape

(30,)

In [18]:
knn_classfier_is = KNNClassifier(6)

In [19]:
knn_classfier_is.fit(X_train, y_train)

In [20]:
y_predict = knn_classfier_is.predict(X_test)
y_predict

array([1, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 2, 2, 2, 1, 2, 1, 1])

In [21]:
y_test

array([1, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 1, 0, 1, 0, 0,
       1, 2, 2, 1, 1, 2, 2, 1])

In [22]:
sum(y_predict==y_test)

26

In [23]:
sum(y_predict==y_test)/len(y_test)

0.8666666666666667

In [ ]:
# sk 也有数据集分割函数

In [24]:
from sklearn.model_selection import train_test_split

In [ ]:
# X_train, X_test ,  y_train, y_test 