In [3]:
a = 100
b = 100
a + b

200

In [4]:
a

100

In [2]:
print('hello')

hello


In [ ]:
import numpy as np
np.__version__

In [6]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
[[i for i in range(5)] for _ in range(3)]

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]

# Numpy

In [8]:
import numpy as np

In [12]:
np_arr = np.array([12, 3, 33, 332])
np_arr

array([ 12,   3,  33, 332])

In [13]:
type(np_arr)

numpy.ndarray

In [17]:
np_arr2  = np.array([float(i) for i in range(10)])
np_arr2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [18]:
np_arr2.dtype

dtype('float64')

In [19]:
# 3
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# numpy数据的常见属性

In [20]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
X = np.arange(16).reshape((4, -1))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
x.ndim

1

In [29]:
X.ndim

2

In [30]:
x.shape

(10,)

In [31]:
X.shape

(4, 4)

In [32]:
x.size

10

In [33]:
X.size

16

In [35]:
# 数据访问
x[3]

3

In [38]:
X[1][1]

5

In [39]:
X[1,1]
# X【行， 列】

5

In [41]:
x[2:7]

array([2, 3, 4, 5, 6])

In [42]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
X[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [46]:
X[:2, 2:]

array([[2, 3],
       [6, 7]])

In [48]:
X[2:, 1:3]

array([[ 9, 10],
       [13, 14]])

# 运算

In [52]:
X= np.arange(1, 16).reshape((3, -1))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [53]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [54]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [56]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [57]:
# 矩阵的相乘

In [58]:
A = np.arange(1, 5).reshape(2, 2)
A

array([[1, 2],
       [3, 4]])

In [61]:
B = np.arange(4, 10).reshape(2, 3)
B

array([[4, 5, 6],
       [7, 8, 9]])

In [64]:
A.dot(B)

array([[18, 21, 24],
       [40, 47, 54]])

In [65]:
np.sum(X)

120

# argsort

In [66]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.random.shuffle(x)

In [68]:
x

array([6, 1, 7, 0, 9, 4, 5, 8, 3, 2])

In [69]:
np.argsort(x) # 返回排序后的索引

array([3, 1, 9, 8, 5, 6, 0, 2, 7, 4], dtype=int64)

# 布尔索引

In [72]:
x = np.sort(x)

In [73]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [75]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False])

In [76]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
np.sum(x>=5)

5