# 读取 csv

In [9]:
import pandas as pd

In [11]:
df = pd.read_csv('dangdang.csv')

In [12]:
df.head()

Unnamed: 0                                          book_name  price  \
0           0   机器学习 周志华 西瓜书 深度学习deep learning 花书 ai书 python神...  423.8   
1           1   机器学习 周志华 西瓜书 深度学习deep learning 花书 ai书 python神...  416.0   
2           2   机器学习 周志华 西瓜书 深度学习deep learning 花书 ai书 python神...  375.3   
3           3   机器学习 周志华 西瓜书 深度学习deep learning 花书 ai书 python神...  274.0   
4           4   Python编程从入门到实践+零基础入门学习Python+Python基础教程第二版（修订...  237.5   

       store                                         link  
0   育博彦图书专营店  http://product.dangdang.com/1604298621.html  
1   阅微阁图书专营店  http://product.dangdang.com/1665183692.html  
2    嘉辰图书专营店  http://product.dangdang.com/1769915860.html  
3  天意事成图书专营店  http://product.dangdang.com/1627535934.html  
4  博鸿文化图书专营店  http://product.dangdang.com/1427665587.html

In [15]:
type(df['price'])

pandas.core.series.Series

In [16]:
type(df.head())

pandas.core.frame.DataFrame

In [19]:
df['price'].values

array([423.8 , 416.  , 375.3 , 274.  , 237.5 , 208.55, 208.  , 208.  ,
       194.5 , 189.  , 181.4 , 177.85, 176.46, 172.9 , 165.01, 164.6 ,
       163.54, 158.98, 157.76, 138.  , 132.94, 128.  , 124.  , 115.1 ,
       104.  ,  89.84,  89.7 ,  88.98,  88.  ,  87.  ,  87.  ,  86.17,
        85.  ,  84.  ,  81.9 ,  81.9 ,  81.67,  80.1 ,  80.1 ,  80.  ,
        79.  ,  75.82,  75.59,  69.8 ,  69.  ,  66.8 ,  66.8 ,  64.  ,
        64.  ,  61.  ,  59.7 ,  53.16,  52.5 ,  50.7 ,  50.  ,  48.  ,
        47.5 ,  45.5 ,  44.5 ,   0.  ])

# 数据归一化

In [21]:
from sklearn import datasets
from matplotlib import pyplot as plt
import numpy as np

In [23]:
x = np.random.randint(0, 100, size=100)
x

array([21, 26, 89,  7, 91, 55, 70, 72, 40, 65,  5, 87, 26, 72, 65, 86, 75,
       86, 98, 82, 75, 42, 15,  8, 35, 40, 17, 22, 43,  8, 76, 70, 91, 42,
       22, 41, 87, 62, 59, 74, 36, 45, 69, 95, 69, 98, 69, 24, 70,  0, 76,
        9, 13, 45, 28, 84,  0, 69, 86, 25, 50, 57,  3, 20, 44, 28, 35, 23,
       73, 95, 94, 41, 54, 38, 58, 86, 42, 15, 81, 36, 73,  1, 49, 93, 55,
       14, 15, 97, 20, 82, 74, 20, 96, 64,  5, 99,  6, 53, 83, 28])

In [24]:
[(x-np.min(x))/np.max(x)-np.min(x)]

[array([0.21212121, 0.26262626, 0.8989899 , 0.07070707, 0.91919192,
        0.55555556, 0.70707071, 0.72727273, 0.4040404 , 0.65656566,
        0.05050505, 0.87878788, 0.26262626, 0.72727273, 0.65656566,
        0.86868687, 0.75757576, 0.86868687, 0.98989899, 0.82828283,
        0.75757576, 0.42424242, 0.15151515, 0.08080808, 0.35353535,
        0.4040404 , 0.17171717, 0.22222222, 0.43434343, 0.08080808,
        0.76767677, 0.70707071, 0.91919192, 0.42424242, 0.22222222,
        0.41414141, 0.87878788, 0.62626263, 0.5959596 , 0.74747475,
        0.36363636, 0.45454545, 0.6969697 , 0.95959596, 0.6969697 ,
        0.98989899, 0.6969697 , 0.24242424, 0.70707071, 0.        ,
        0.76767677, 0.09090909, 0.13131313, 0.45454545, 0.28282828,
        0.84848485, 0.        , 0.6969697 , 0.86868687, 0.25252525,
        0.50505051, 0.57575758, 0.03030303, 0.2020202 , 0.44444444,
        0.28282828, 0.35353535, 0.23232323, 0.73737374, 0.95959596,
        0.94949495, 0.41414141, 0.54545455, 0.38

In [27]:
X = np.random.randint(0, 100, size=(50, 2))
X.shape

(50, 2)

In [28]:
X[:10, :]

array([[59, 10],
       [28, 19],
       [33,  2],
       [ 7, 40],
       [14, 99],
       [37,  7],
       [87, 72],
       [56, 30],
       [61, 99],
       [ 7, 55]])

In [29]:
X = np.array(X, dtype=float)

In [30]:
X[:10, :]

array([[59., 10.],
       [28., 19.],
       [33.,  2.],
       [ 7., 40.],
       [14., 99.],
       [37.,  7.],
       [87., 72.],
       [56., 30.],
       [61., 99.],
       [ 7., 55.]])

In [32]:
X[:, 0] = (X[:, 0]- np.min(X[:, 0]))/(np.max(X[:, 0])-np.min(X[:, 0]))

In [33]:
X[:, 0]

array([0.5959596 , 0.28282828, 0.33333333, 0.07070707, 0.14141414,
       0.37373737, 0.87878788, 0.56565657, 0.61616162, 0.07070707,
       0.98989899, 0.84848485, 0.62626263, 0.43434343, 0.6969697 ,
       0.15151515, 0.77777778, 0.42424242, 0.        , 0.82828283,
       0.16161616, 0.42424242, 1.        , 0.57575758, 0.84848485,
       0.        , 0.63636364, 0.55555556, 0.4040404 , 0.2020202 ,
       0.3030303 , 0.11111111, 0.78787879, 0.51515152, 0.57575758,
       0.57575758, 0.44444444, 0.85858586, 0.88888889, 0.62626263,
       0.29292929, 0.15151515, 0.8989899 , 0.        , 0.72727273,
       0.15151515, 0.72727273, 0.63636364, 0.74747475, 0.35353535])

In [36]:
X[:, 1}= (X[:, 1- np.min(X[:, 1))/(np.max(X[:, 1)-np.min(X[:, 1))

SyntaxError: invalid syntax (<ipython-input-36-7f89ed66d7fe>, line 1)